import type { Metadata } from "next";
import "./globals.css";
import { Sora } from 'next/font/google';
import Header from "@/components/sections/Header";
import Footer from "@/components/sections/Footer";

const sora = Sora({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: "Portfolio - Mini Hackathon",
  description: "Generated by Owais Abdullah",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={sora.className}>
      <body>
        <Header />
        {children}
        
        <Footer />
      </body>
    </html>
  );
}
